services:
  sql-server:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: sql-server
    volumes:
      - sql-server:/var/opt/mssql
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Passw@rd
      - MSSQL_PID=Developer
      - MSSQL_USER=SA
      - MSSQL_PASSWORD=Passw@rd
volumes:
  sql-server: