CREATE TABLE
    Grocery.List (
        ListID UNIQUEIDENTIFIER NOT NULL CONSTRAINT DFListPK DEFAULT NEWSEQUENTIALID (),
        List NVARCHAR (50) NOT NULL CONSTRAINT DFListList DEFAULT '',
        CreatedDate DATETIMEOFFSET NOT NULL CONSTRAINT DFListCreatedDate DEFAULT GETUTCDATE ()
    );