CREATE TABLE
    Grocery.Store (
        StoreID UNIQUEIDENTIFIER NOT NULL CONSTRAINT DFStorePK DEFAULT NEWSEQUENTIALID (),
        Store NVARCHAR (50) NOT NULL CONSTRAINT DFStoreStore DEFAULT ''
    );